//! Adversarial cross-check against the REAL Python on edge cases the committed
//! fixtures don't reach (non-ASCII passthrough, float/banker's-rounding bboxes,
//! palette caps, art/photo branch selection, custom mediums, extras ordering).
//!
//! The oracle is generated by `edge_oracle.py` running ai-toolkit's own code and
//! its path is passed via EDGE_ORACLE. When the env var is unset (e.g. CI on a
//! machine without that scratch file) the test is skipped, so it never breaks
//! the committed gate — it is a developer cross-check, not part of the shipped
//! parity contract.

use ideogram_caption::{canon_medium, digest_caption_string, normalize_hex, swap_bbox_xy_in_text};
use serde_json::Value;

#[test]
fn edge_cross_check() {
    let path = match std::env::var("EDGE_ORACLE") {
        Ok(p) => p,
        Err(_) => {
            eprintln!("EDGE_ORACLE unset; skipping adversarial cross-check");
            return;
        }
    };
    let bytes = std::fs::read(&path).expect("read edge oracle");
    let fx: Value = serde_json::from_slice(&bytes).expect("parse edge oracle");

    let mut total = 0;
    let mut fails: Vec<String> = Vec::new();

    for c in fx["digest_caption_string"].as_array().unwrap() {
        total += 1;
        let i = c["in"].as_str().unwrap();
        let e = c["out"].as_str().unwrap();
        let g = digest_caption_string(i);
        if g != e {
            fails.push(format!("digest\n IN {i:?}\n EXP {e:?}\n GOT {g:?}"));
        }
    }
    for c in fx["swap_bbox_xy_in_text"].as_array().unwrap() {
        total += 1;
        let i = c["in"].as_str().unwrap();
        let e = c["out"].as_str().unwrap();
        let g = swap_bbox_xy_in_text(i);
        if g != e {
            fails.push(format!("swap\n IN {i:?}\n EXP {e:?}\n GOT {g:?}"));
        }
    }
    for c in fx["canon_medium"].as_array().unwrap() {
        total += 1;
        let i = c["in"].as_str().unwrap();
        let e = c["out"].as_str().unwrap();
        let g = canon_medium(i);
        if g != e {
            fails.push(format!("canon\n IN {i:?}\n EXP {e:?}\n GOT {g:?}"));
        }
    }
    for c in fx["normalize_hex"].as_array().unwrap() {
        total += 1;
        let i = c["in"].as_str().unwrap();
        let g = normalize_hex(i);
        let ok = match &c["out"] {
            Value::Null => g.is_none(),
            Value::String(s) => g.as_deref() == Some(s.as_str()),
            _ => false,
        };
        if !ok {
            fails.push(format!("hex\n IN {i:?}\n EXP {:?}\n GOT {g:?}", c["out"]));
        }
    }

    eprintln!("edge cross-check: {}/{} pass", total - fails.len(), total);
    assert!(fails.is_empty(), "edge failures:\n{}", fails.join("\n\n"));
}
