//! Adversarial cross-check of the B/C glue against the REAL Python on edge cases
//! the committed fixtures don't reach (lazy multi-fence extract_json, CRLF/no-
//! newline fences, two-object span→None, bool/string/null bbox values, art-branch
//! migration + non-ASCII in full_glue, empty/null aspect_ratio fallback, snap-path
//! compute_aspect_ratio, and the `{{placeholder}}`-in-original_prompt ordering trap).
//!
//! The oracle is generated by `glue_edge_oracle.py` (ai-toolkit's own code) and
//! located via GLUE_EDGE_ORACLE; the test self-skips when unset so it never
//! breaks the committed gate — it is a developer cross-check, not the contract.

use ideogram_caption::glue;
use serde_json::Value;

fn sha256_hex_chars(s: &str) -> (String, usize) {
    (super_sha::sha256_hex(s.as_bytes()), s.chars().count())
}

#[test]
fn glue_edge_cross_check() {
    let path = match std::env::var("GLUE_EDGE_ORACLE") {
        Ok(p) => p,
        Err(_) => {
            eprintln!("GLUE_EDGE_ORACLE unset; skipping glue adversarial cross-check");
            return;
        }
    };
    let fx: Value =
        serde_json::from_slice(&std::fs::read(&path).expect("read glue edge oracle")).expect("parse");
    let mut total = 0usize;
    let mut fails: Vec<String> = Vec::new();

    macro_rules! check {
        ($cond:expr, $msg:expr) => {{
            total += 1;
            if !($cond) {
                fails.push($msg);
            }
        }};
    }

    for c in fx["extract_json"].as_array().unwrap() {
        let i = c["in"].as_str().unwrap();
        let got = glue::extract_json(i);
        let ok = opt_eq(&c["out"], &got);
        check!(ok, format!("extract_json in={i:?} exp={} got={:?}", c["out"], got));
    }
    for c in fx["b_convert_bbox"].as_array().unwrap() {
        let got = glue::b_convert_bbox(&c["in"]);
        check!(opt_eq(&c["out"], &got), format!("b_convert_bbox in={} exp={} got={:?}", c["in"], c["out"], got));
    }
    for c in fx["c_sanitize_bbox"].as_array().unwrap() {
        let got = glue::c_sanitize_bbox(&c["in"]);
        check!(opt_eq(&c["out"], &got), format!("c_sanitize_bbox in={} exp={} got={:?}", c["in"], c["out"], got));
    }
    for c in fx["b_full_glue"].as_array().unwrap() {
        let i = c["in"].as_str().unwrap();
        let exp = c["out"].as_str().unwrap();
        let got = glue::b_full_glue(i);
        check!(got == exp, format!("b_full_glue in={i:?}\n  EXP={exp:?}\n  GOT={got:?}"));
    }
    for c in fx["c_full_glue"].as_array().unwrap() {
        let i = c["in"].as_str().unwrap();
        let got = glue::c_full_glue(i);
        let ok = match &c["out"] {
            Value::Null => got.is_none(),
            Value::String(s) => got.as_deref() == Some(s.as_str()),
            _ => false,
        };
        check!(ok, format!("c_full_glue in={i:?}\n  EXP={}\n  GOT={:?}", c["out"], got));
    }
    for c in fx["c_normalize_item"].as_array().unwrap() {
        let dar = c["default_ar"].as_str().unwrap();
        let got = glue::normalize_item(&c["in"], dar);
        let ok = match &c["out"] {
            Value::Null => got.is_none(),
            Value::Array(a) => got.as_ref().map(|(i, r)| i == a[0].as_str().unwrap() && r == a[1].as_str().unwrap()).unwrap_or(false),
            _ => false,
        };
        check!(ok, format!("c_normalize_item in={} exp={} got={:?}", c["in"], c["out"], got));
    }
    for c in fx["compute_aspect_ratio"].as_array().unwrap() {
        let wh = c["in"].as_array().unwrap();
        let got = glue::compute_aspect_ratio(wh[0].as_i64().unwrap(), wh[1].as_i64().unwrap());
        let exp = c["out"].as_str().unwrap();
        check!(got == exp, format!("compute_aspect_ratio in={} exp={exp:?} got={got:?}", c["in"]));
    }
    // build_prompt oracle: out = [sha256, char_len, head[:120], tail[-200:]]
    for c in fx["b_build_prompt"].as_array().unwrap() {
        let inp = &c["in"];
        let cp = match inp.get("cp") {
            Some(Value::String(s)) => Some(s.as_str()),
            _ => None,
        };
        let ar = inp["ar"].as_str().unwrap();
        let got = glue::b_build_prompt(cp, ar);
        check_bp("b_build_prompt", &c["out"], &got, &mut total, &mut fails);
    }
    for c in fx["c_build_prompt"].as_array().unwrap() {
        let inp = &c["in"];
        let ar = inp["ar"].as_str().unwrap();
        let op = inp["op"].as_str().unwrap();
        let cr = inp["cr"].as_bool().unwrap();
        let ins = inp["ins"].as_str().unwrap();
        let got = glue::c_build_prompt(glue::C_UPSAMPLE_PROMPT, ar, op, cr, ins);
        check_bp("c_build_prompt", &c["out"], &got, &mut total, &mut fails);
    }

    eprintln!("glue edge cross-check: {}/{} pass", total - fails.len(), total);
    assert!(fails.is_empty(), "glue edge failures:\n{}", fails.join("\n\n"));
}

fn check_bp(name: &str, expected: &Value, got: &str, total: &mut usize, fails: &mut Vec<String>) {
    let a = expected.as_array().unwrap();
    let exp_sha = a[0].as_str().unwrap();
    let exp_len = a[1].as_u64().unwrap() as usize;
    let exp_head = a[2].as_str().unwrap();
    let exp_tail = a[3].as_str().unwrap();
    let (got_sha, got_len) = sha256_hex_chars(got);
    let head: String = got.chars().take(exp_head.chars().count()).collect();
    let chars: Vec<char> = got.chars().collect();
    let tail: String = chars[chars.len().saturating_sub(exp_tail.chars().count())..].iter().collect();
    let ok = got_sha == exp_sha && got_len == exp_len && head == exp_head && tail == exp_tail;
    *total += 1;
    if !ok {
        fails.push(format!(
            "[{name}] sha exp={exp_sha} got={got_sha}; len exp={exp_len} got={got_len}; head_ok={} tail_ok={}",
            head == exp_head, tail == exp_tail
        ));
    }
}

fn opt_eq(expected: &Value, got: &Option<Value>) -> bool {
    match (expected, got) {
        (Value::Null, None) => true,
        (Value::Null, Some(_)) => false,
        (exp, Some(g)) => exp == g,
        (_, None) => false,
    }
}

// Reuse a local SHA-256 (same as the gate test) so this dev check has no dep.
mod super_sha {
    pub fn sha256_hex(data: &[u8]) -> String {
        let d = sha256(data);
        let mut s = String::with_capacity(64);
        for b in d {
            s.push_str(&format!("{:02x}", b));
        }
        s
    }
    fn sha256(data: &[u8]) -> [u8; 32] {
        const K: [u32; 64] = [
            0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
            0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
            0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
            0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
            0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
            0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
            0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
            0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
        ];
        let mut h: [u32; 8] = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
        let mut msg = data.to_vec();
        let bit_len = (data.len() as u64) * 8;
        msg.push(0x80);
        while msg.len() % 64 != 56 {
            msg.push(0);
        }
        msg.extend_from_slice(&bit_len.to_be_bytes());
        for block in msg.chunks(64) {
            let mut w = [0u32; 64];
            for i in 0..16 {
                w[i] = u32::from_be_bytes([block[i * 4], block[i * 4 + 1], block[i * 4 + 2], block[i * 4 + 3]]);
            }
            for i in 16..64 {
                let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
                let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
                w[i] = w[i - 16].wrapping_add(s0).wrapping_add(w[i - 7]).wrapping_add(s1);
            }
            let (mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh) = (h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]);
            for i in 0..64 {
                let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
                let ch = (e & f) ^ ((!e) & g);
                let t1 = hh.wrapping_add(s1).wrapping_add(ch).wrapping_add(K[i]).wrapping_add(w[i]);
                let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
                let maj = (a & b) ^ (a & c) ^ (b & c);
                let t2 = s0.wrapping_add(maj);
                hh = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
            }
            h[0] = h[0].wrapping_add(a); h[1] = h[1].wrapping_add(b); h[2] = h[2].wrapping_add(c); h[3] = h[3].wrapping_add(d);
            h[4] = h[4].wrapping_add(e); h[5] = h[5].wrapping_add(f); h[6] = h[6].wrapping_add(g); h[7] = h[7].wrapping_add(hh);
        }
        let mut out = [0u8; 32];
        for (i, word) in h.iter().enumerate() {
            out[i * 4..i * 4 + 4].copy_from_slice(&word.to_be_bytes());
        }
        out
    }
}
